#:kivy 1.11.1

<SAQScreen>:
    name: "saq"

    MDBoxLayout:
        orientation: "vertical"

        MyLabel:
            text: "full form of BAA"
            halign: "center"
            size_hint_y: 0.1

        LineDivider:

        AnchorLayout:
            anchor_x: "center"
            padding: 50

            MDTextField:
                hint_text: "Answer"
                mode: "rectangle"
    
        SubmitAnchor:
            SubmitButton: